### ISSUE TITLE
the server closed before I choose download in my phone's browser.

### ISSUE THREAD

**Issue by ginhton** [claudiodangelis/qr-filetransfer#13] opened 2018-03-23 01:59 UTC
I scan QR code in my browser. And choose download that file. Then the server closed, I have no idea how to download that.
Thank you for any suggestions.

**Comment by joyme123** [comment] 2018-03-23 07:55
[see this pr](https://github.com/claudiodangelis/qr-filetransfer/pull/21)

**Comment by Dolondro** [comment] 2018-03-23 12:50
In the case of some barcode scanning applications, the app will do it's own internal fetch to the URL rather than directly referring you to the browser.

This seems to be the case with the commonly used `Barcode Scanner` application on Android, and I suspect it may be done automatically by most apps that use the library that it seems to be using underneath, [Zxing](https://github.com/zxing/zxing)

![image](https://user-images.githubusercontent.com/1678803/37829817-72f83536-2e98-11e8-9fd6-8f5e4459a995.png)

I suspect the best way of handling this is to either put in some kind of "don't auto close flag" or the more hacky but potentially more useful not closing the connection depending on the user-agent of the initial request.

**Comment by claudiodangelis** [comment] 2018-03-26 21:48
As I mentioned in [this comment](https://github.com/claudiodangelis/qr-filetransfer/pull/21#issuecomment-376315246), I would like to retain the auto close ability. Let's continue researching a solution, I'm pretty sure we will find one; thanks for showing interest in this!

**Comment by beac0n** [comment] 2018-03-28 06:16
@claudiodangelis I'm having the same Issue.
I agree, that the feature of auto closing should not be removed.
However, couldn't we add a command line parameter which disables the auto-close feature? 
That way the user can decide for themselfs what to use

**Comment by claudiodangelis** [comment] 2018-03-28 09:06
Agreed @beac0n, while we work out a definitive fix for this, we can have a flag that prevents the tool from automatically closing.

The patch would look like this:

```go

var autocloseFlag = flag.Bool("autoclose", true, ".....") 

. . .

if *autoclose == true {
    os.Exit(0)
}
```

Usage would be:

```
./qr-filetransfer -autoclose=false myfile.pdf
```

Thoughts? Maybe we can find a better flag name for `autoclose` (or for using a complement)?

To @joyme123: you submitted a PR for this issue a few days back, do you want to apply these changes?

**Comment by tssva** [comment] 2018-03-28 22:55
The parallel-downloads branch on my fork fixes this issue. At least for ZXing. In my testing it has also been successful in allowing parallel downloads to succeed while still allowing for auto-closing. I need more testing to be done. So far the parallel downloads have only been tested using Chrome 65 on Android. Also as is it allows multiple clients to connect and when the first one completes a download the application exits. I have an idea on how to fix it, but would like to have more people test the parallel downloading to make sure I'm on the right track before investing more.

Time constraints mean I won't be able to get a PR submitted until probably tomorrow, but feel free to grab it from my fork.

**Comment by tssva** [comment] 2018-03-29 18:15
Found a couple of issues with the code. As is it does happen to allow the transfer to complete sometimes but not consistently. Know the issue and will be updating the code today.

**Comment by claudiodangelis** [comment] 2018-04-06 09:12
Hello @ginhton @Dolondro @beac0n and @jerson, could you please help testing the fix provided by @tssva?

Instructions:
```
# From the cloned repository...
git fetch origin pull/54/head:parallel-downloads
git checkout parallel-downloads
go build
./qr-filetransfer /path/to/the/problematic/file
```

Thanks :+1:

**Comment by Dolondro** [comment] 2018-04-06 09:55
I can confirm that this fixes the issue for me :+1:

**Closed** 2018-04-17 13:52 UTC
Labels: bug, ready but needs testing, someone is working on this
