### ISSUE TITLE
How to deal  distorted  qr code [windows can't recognize]

### ISSUE THREAD

**Issue by drduan** [claudiodangelis/qr-filetransfer#32] opened 2018-03-25 12:24 UTC
![2018-03-25_202329](https://user-images.githubusercontent.com/7875572/37874929-9913f696-306a-11e8-8acf-03bd234fd245.png)

**Comment by claudiodangelis** [comment] 2018-03-25 18:51
Hi @drduan, thanks for reaching out. It looks that the font you are using is not monospace, can you please confirm that:
1. the font is not monospace
2. it works with a monospace font
?

Thank you!

**Comment by claudiodangelis** [comment] 2018-03-25 18:56
Also, it looks that you are using an IPv6, for which support is still buggy (there is an issue already opened for this: https://github.com/claudiodangelis/qr-filetransfer/issues/4), so it's probably not going to work even after getting the QR code, sorry for that! I hope to fix the problem with IPv6 real soon.

**Comment by mattn** [comment] 2018-03-27 03:48
This is caused by font. The letters using qrterminal are ambigous width in UTF-8. you should use monospace font. Or patch this.

```diff
diff --git a/main.go b/main.go
index e9b082e..a4a9fa0 100644
--- a/main.go
+++ b/main.go
@@ -7,7 +7,9 @@ import (
 	"net"
 	"net/http"
 	"os"
+	"runtime"
 
+	"github.com/mattn/go-colorable"
 	"github.com/mdp/qrterminal"
 )
 
@@ -49,8 +51,19 @@ func main() {
 	// Generate the QR code
 	fmt.Println("Scan the following QR to start the download.")
 	fmt.Println("Make sure that your smartphone is connected to the same WiFi network as this computer.")
-	qrterminal.GenerateHalfBlock(fmt.Sprintf("http://%s", listener.Addr().String()),
-		qrterminal.L, os.Stdout)
+	qrcfg := qrterminal.Config{
+		Level:      qrterminal.L,
+		HalfBlocks: true,
+	}
+	if runtime.GOOS == "windows" {
+		qrcfg.Level = qrterminal.L
+		qrcfg.HalfBlocks = false
+		qrcfg.Writer = colorable.NewColorableStdout()
+		qrcfg.BlackChar = qrterminal.BLACK
+		qrcfg.WhiteChar = qrterminal.WHITE
+	}
+
+	qrterminal.GenerateWithConfig(fmt.Sprintf("http://%s", listener.Addr().String()), qrcfg)
 
 	// Define a default handler for the requests
 	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
```

**Comment by mattn** [comment] 2018-03-27 03:50
BTW, current implementation of qrterminal is wrong direction to draw.

https://github.com/mdp/qrterminal/pull/6

So some camera application failure to scan QR code.

**Comment by mattn** [comment] 2018-03-27 03:56
@claudiodangelis if you want this patch, I'll send PR.

**Comment by NatoBoram** [comment] 2018-04-05 23:11
QR Code looks good, and IPv6 worked perfectly.

![qr-powershell](https://user-images.githubusercontent.com/10495562/38396153-66e70e2c-3904-11e8-9c76-d0236c88fdf9.PNG)

**Comment by claudiodangelis** [comment] 2018-04-06 06:07
Thanks @NatoBoram, let's wait to hear from @drduan then we can close this.

**Comment by claudiodangelis** [comment] 2018-05-01 17:57
After 26 days, 0 answers from OP and 0 new complaints I'm assuming this is fixed.

**Closed by claudiodangelis** 2018-05-01 17:57 UTC
Labels: someone is working on this
